name: nAmE

ghc-options: -Wall -Wno-unused-matches
language: GHC2021
default-extensions:
  - OverloadedStrings
  - LambdaCase
  - RecursiveDo
  - DeriveGeneric
  - BlockArguments
  - TypeFamilies
  - FunctionalDependencies
  - RecordWildCards
  - ApplicativeDo
dependencies:
  - base
  - reflex

executables:
  app:
    source-dirs: app
    main: Main.hs
